version: "3.9"
services:
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > APP - API
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  webapi:
    build:
      context: ./
      args:
        PUB_ENV: Staging
    container_name: webapi
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Staging
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - mssql-srv
      - redis-srv
#      - rabbitmq-srv
#      - elk-es01
#      - elk-es02
#      - elk-es03
#      - elk-kibana

    ports: 
      - "2030:80"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > SQLSERVER
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  mssql-srv:
    build: ./Containers/services/sqlserver
    container_name: mssql-srv
    volumes:
      - sqlserver_data:/var/lib/mssql/data
    ports:
      - '1350:1433'
    restart: always
    networks:
      - devnet
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > ELK - ELASTIC 01
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  elk-es01:
    build: ./Containers/services/elk/elasticsearch
    container_name: elk-es01
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=elk-es01
      - discovery.seed_hosts=elk-es02,elk-es03
      - cluster.initial_master_nodes=elk-es01,elk-es02,elk-es03
    volumes:
      - /etc/localtime:/etc/localtime
      # - ./Containers/volumes/elk/es01:/usr/share/elasticsearch/data
    ports: 
      - "22110:9200"
    networks:
      - devnet
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  elk-es02:
    build: ./Containers/services/elk/elasticsearch
    container_name: elk-es02
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=elk-es02
      - discovery.seed_hosts=elk-es01,elk-es03
      - cluster.initial_master_nodes=elk-es01,elk-es02,elk-es03
    volumes:
      - /etc/localtime:/etc/localtime
      # - ./Containers/volumes/elk/es02:/usr/share/elasticsearch/data
    ports: 
      - "22120:9200"
    networks:
      - devnet
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  elk-es03:
    build: ./Containers/services/elk/elasticsearch
    container_name: elk-es03
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=elk-es03
      - discovery.seed_hosts=elk-es01,elk-es02
      - cluster.initial_master_nodes=elk-es01,elk-es02,elk-es03
    volumes:
      - /etc/localtime:/etc/localtime
      # - ./Containers/volumes/elk/es01:/usr/share/elasticsearch/data
    ports: 
      - "22130:9200"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > ELK - KIBANA
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  elk-kibana:
    build: ./Containers/services/elk/kibana
    container_name: elk-kibana
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on: 
      - elk-es01
    volumes:
      - /etc/localtime:/etc/localtime
    ports: 
      - "22210:5601"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > ELK - LOGSTASH
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  elk-logstash:
    build: ./Containers/services/elk/logstash
    container_name: elk-logstash
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on: 
      - elk-es02
    volumes:
      - /etc/localtime:/etc/localtime
    ports: 
      - "22310:9600"
      - "22320:8010"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > MYSQL
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~

  mysql-srv:
    build: ./Containers/services/mysql
    container_name: mysql-srv
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
      # - ./volumes/mysql/datadir:/var/lib/mysql
    ports: 
      - "33100:3306"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > POSTGRES
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~

  pgsql-srv:
    build: ./Containers/services/postgresql
    container_name: pgsql-srv
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
      # - ./volumes/postgresql/backup:/var/lib/postgresql/backup
      # - ./volumes/postgresql/data:/var/lib/postgresql/data
    ports: 
      - "33110:5432"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > POSTGRES
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~

  mongodb-srv:
    build: ./Containers/services/mongodb
    container_name: mongodb-srv
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
      # - ./volumes/mongodb/backup:/data/backup
      # - ./volumes/mongodb/data:/data/db
      # - ./volumes/mongodb/config:/data/configdb
    ports: 
      - "33210:27017"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > REDIS
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  redis-srv:
    build: ./Containers/services/redis
    container_name: redis-srv
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime
      - redis_data:/data
    ports: 
      - "33310:6379"
    networks:
      - devnet

  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  # > RABBIT MQ
  # ~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~--~
  rabbitmq-srv:
    build: ./Containers/services/rabbitmq
    container_name: rabbitmq-srv
    restart: on-failure
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime
      - rabbitmq_data:/var/lib/rabbitmq
    ports: 
      - "33410:5672"
      - "33415:15672"
    networks:
      - devnet


networks:
  devnet:

volumes:
  sqlserver_data: {}
  redis_data: {}
  rabbitmq_data: {}
  # elastic01_data: {}
  # elastic02_data: {}
  # elastic03_data: {}