FROM docker.elastic.co/kibana/kibana:7.14.0

ENV SERVER_NAME=elk-kibana
ENV ELASTICSEARCH_HOSTS='["http://elk-es01:9200"]'

#ELASTICSEARCH_URL='["http://elk-es01:9200"]'
#ENV ELASTICSEARCH_HOSTS='["http://elk-es01:9200","http://elk-es02:9200","http://elk-es03:9200"]'
EXPOSE 5601