FROM mysql:8.0.26

LABEL title="DigiPay Dev MySql"
LABEL description="Latest postgresql wrapper image for development use."
LABEL "com.mydigipay.image.author"="Ehsan Maleki Zoeram"
LABEL "com.mydigipay.image.vendor"="DigiPay Fintech Co."

ENV MYSQL_ROOT_PASSWORD=b61dULNhRWofcMEY

EXPOSE 3306
