FROM rabbitmq:management

COPY ./config/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY ./config/advanced.config /etc/rabbitmq/advanced.config

# Management
EXPOSE 4369 5671 5672 15691 15692 25672 15671 15672